import os

from PyQt6.QtCore import QRect, QSize
from PyQt6.QtGui import QImage

WINDOW_SIZE = 960, 640

MARGIN_LEFT = 52
MARGIN_TOP = 20

WORK_PILE_Y = 165
WORK_OFFSET_Y = 32


BUTTON_DIMENSIONS = QSize(60,40)
CARD_DIMENSIONS = QSize(88, 120)
CARD_RECT = QRect(0, 0, CARD_DIMENSIONS.width(), CARD_DIMENSIONS.height())

CARD_SPACING_X = CARD_DIMENSIONS.width() + 22

BUTTON_MARGIN_X = MARGIN_LEFT + 3*CARD_SPACING_X + 15
BUTTON_MARGIN_Y = 20
BUTTON_SPACING_Y = 40

